language: node_js
cache:
  yarn: true
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache
    - node_modules
node_js:
  - '8'
  - '10'
install:
  - yarn bootstrap
script:
  - yarn test-ci
notifications:
  email: false
git:
  depth: 5
