$(document).ready(function(){
  $("#menu-arte").hover(function(){
    $('.menu').toggleClass('arte');
    $('.preview').toggleClass('arte');
  })
  $("#menu-overkiz").hover(function(){
    $('.menu').toggleClass('overkiz');
    $('.preview').toggleClass('overkiz');
  })
  $("#menu-somfy").hover(function(){
    $('.menu').toggleClass('somfy');
    $('.preview').toggleClass('somfy');
  })
  $("#menu-orange").hover(function(){
    $('.menu').toggleClass('orange');
    $('.preview').toggleClass('orange');
  })
  $("#menu-ooredoo").hover(function(){
    $('.menu').toggleClass('ooredoo');
    $('.preview').toggleClass('ooredoo');
  })
  $("#menu-welcomhere").hover(function(){
    $('.menu').toggleClass('welcomhere');
    $('.preview').toggleClass('welcomhere');
  })
  $("#menu-mordu").hover(function(){
    $('.menu').toggleClass('mordu');
    $('.preview').toggleClass('mordu');
  })
  $("#menu-hitachi").hover(function(){
    $('.menu').toggleClass('hitachi');
    $('.preview').toggleClass('hitachi');
  })
  $("#menu-devialet").hover(function(){
    $('.menu').toggleClass('devialet');
    $('.preview').toggleClass('devialet');
  })
  $("#menu-simplon").hover(function(){
    $('.menu').toggleClass('simplon');
    $('.preview').toggleClass('simplon');
  })
});